# Numpy Exercise for AI 240  - 10459          

Instructor- Dr. Uma Gajendragadkar

### Exercise 1.1 - If Numpy is not already installed then please install Numpy using below instruction
!pip install Numpy      

### Exercise 1.2 # Import Numpy package using below instruction 
import numpy as np

### Exercise 1.3 ## Example Usage Read below example and execute the cell

data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)

### Exercise 1.4 Do all exercises from Lecture slides. Refer slides shared after the lecture.

### Exercise 1.5 Searching Arrays - find method of numpy to search an element in array - You can google for the method

Find the indexes where the value is 9:


arr = np.array([3, 2, 14, 9, 10, 12])

### Exercise 1.6 Join two arrays given below and print the result.

arr1 = np.array([9, 5, 8])

arr2 = np.array([55, 89, 76])

### Save and submit your notebook in your Github account.

In [2]:
# Install Numpy
!pip install Numpy

In [3]:
# Import Numpy as np
import numpy as np

In [4]:
# Example usage and execution
data = np.array([1,2,3,4,5])

In [5]:
print(data)

[1 2 3 4 5]


In [6]:
print(len(data))

5


In [7]:
print(type(data))

<class 'numpy.ndarray'>


In [8]:
print(data.shape)

(5,)


In [10]:
import numpy 

arr = numpy.array([10,20,30,40,50])

print(arr)

[10 20 30 40 50]


In [11]:
# Create a 2-D array contining two arrays
import numpy as np

arr = np.array([[10,20,30],[40,50,60]])

print(arr)

[[10 20 30]
 [40 50 60]]


In [12]:
# Get first element from the following array
import numpy as np

arr = np.array([10,20,30,40])

print(arr[0])

10


In [13]:
# SLice elements from index 1 to index 5 from the following array
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5])

[2 3 4 5]


In [14]:
import numpy as np

arr = np.array([30,20,40,10])

print(np.sort(arr))

[10 20 30 40]


In [15]:
import numpy as np

arr = np.array(['kiwi','berry','pear'])

print(np.sort(arr))

['berry' 'kiwi' 'pear']


In [16]:
#Find indexes where value is 9
import numpy as np

arr = np.array([3,2,14,9,10,12])

indices = np.where(arr == 9)

print(indices)

(array([3]),)


In [17]:
# Join two arrays
import numpy as np

arr1 = np.array([9,5,8])
arr2 = np.array([55,89,76])

joined_arr = np.concatenate((arr1, arr2))
print(joined_arr)

[ 9  5  8 55 89 76]
